config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/openebench-nuxt:
      branch: master
      repo: https://github.com/inab/openebench-nuxt
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openebench-nuxt git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-tangerine-bandicoot.sh
        container: qc.acc_messy-red-uguisu
  QC.Doc:
    repos:
      github.com/inab/openebench-nuxt find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-plum-chinchilla.sh
        container: qc.doc_craggy-cinnabar-dalmatian
      github.com/inab/openebench-nuxt git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-cornflower-quail.sh
        container: qc.doc_cloudy-cobalt-cuttlefish
      github.com/inab/openebench-nuxt markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-myrtle-caiman.sh
        container: qc.doc_homely-linen-mandrill
  QC.Lic:
    repos:
      github.com/inab/openebench-nuxt licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-sepia-ant.sh
        container: qc.lic_shabby-asparagus-burmese
  QC.Sty:
    repos:
      github.com/inab/openebench-nuxt jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-goldenrod-gorilla.sh
        container: qc.sty_pokey-mauve-fousek
      github.com/inab/openebench-nuxt stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-brass-ragdoll.sh
        container: qc.sty_gloppy-zucchini-markhor
  QC.Ver:
    repos:
      github.com/inab/openebench-nuxt get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-scarlet-fish.sh
        container: qc.ver_leaky-cobalt-cuscus
timeout: 1800
