config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/openebench-nuxt:
      branch: master
      repo: https://github.com/inab/openebench-nuxt
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openebench-nuxt git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-tan-moose.sh
        container: qc.acc_scanty-yellow-termite
  QC.Doc:
    repos:
      github.com/inab/openebench-nuxt find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-cinnabar-sheepdog.sh
        container: qc.doc_foggy-ochre-jellyfish
      github.com/inab/openebench-nuxt git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-brass-newt.sh
        container: qc.doc_cranky-harlequin-rhinoceros
      github.com/inab/openebench-nuxt markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-crimson-ant.sh
        container: qc.doc_pokey-red-hippopotamus
  QC.Lic:
    repos:
      github.com/inab/openebench-nuxt licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-white-sheep.sh
        container: qc.lic_woolly-amaranth-moth
  QC.Sty:
    repos:
      github.com/inab/openebench-nuxt jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-chocolate-tarsier.sh
        container: qc.sty_randy-grey-armadillo
      github.com/inab/openebench-nuxt stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-tangerine-neanderthal.sh
        container: qc.sty_cloudy-auburn-gar
  QC.Ver:
    repos:
      github.com/inab/openebench-nuxt get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-viridian-squirrel.sh
        container: qc.ver_surly-amber-caiman
timeout: 1800
